- README.md
- cpp/config_actions.h
- cpp/config_classes.h
- cpp/config_exceptions.h
- cpp/config_grammar.h
- cpp/config_helpers.h
- cpp/config_reader.cpp
- cpp/config_test.cpp
- examples/config_example7.cfg
- Adds support for defining `VAR` types within a `struct` that is a sub-object of a `proto`.
- During the `resolveReferences` and `replaceProtoVar` phase, any variables contained within a `struct` will also be resolved.
- Minor improvements to the grammer
- Adds helper macro for throwing exceptions.
> Improves support for `struct`s in `proto`s

- README.md
- cpp/config_actions.h
- cpp/config_grammar.h
- cpp/config_helpers.h
- cpp/utils.h
- examples/config_example8.cfg
- tests/config_grammar_test.cpp
- tests/config_helpers_test.cpp
- Supports using reference variables (e.g. `$VAR`) in value references (e.g. `$(value.ref)`).
- When resolving references, the reference variables will be replaced in the value reference in the same manner that they are replaced within strings containing value references.
- Adds additional tests for the `REF_VAR` grammar rule as well as modifies [`config_example8.cfg`](../blob/main/examples/config_example8.cfg) to make use of and test this new feature.
> Adds support for ref vars in value refs

- cpp/config_grammar.h
- cpp/math_actions.h
- cpp/math_grammar.h
- tests/math_test.cpp
*  Moves ActionData used for `math` into math namespace.
*  Moves common grammar rules from math_grammar.h into `math` namespace.
*  Eliminate duplicate actions in `grammar2` namespace by inheriting
from actions in math namespace.
> Further consolidates math grammar

- cpp/config_actions.h
- cpp/config_grammar.h
- cpp/config_reader.cpp
- examples/config_example1.cfg
- examples/config_example2.cfg
- examples/config_example3.cfg
- examples/config_example4.cfg
- examples/config_example5.cfg
- examples/config_example7.cfg
- examples/config_example8.cfg
- examples/invalid/config_cyclic1.cfg
- examples/invalid/config_cyclic2.cfg
- tests/config_exception_test.cpp
- tests/config_grammar_test.cpp
- tests/config_parse_test.cpp
*  Drops the `end <KEY>` in favor of curly-brace enclosed content.
> Replaces `end` keyword with curly braces

- cpp/config_build.cpp
- cpp/config_helpers.cpp
- cpp/config_helpers.h
- cpp/math_actions.h
*  When attempting to evaluate an expression, if it contains a
sub-expression, evaluate it first.
> Adds sub-expression evaluation

- cpp/config_classes.h
*  Deep-copy the data contained by both the `ConfigStruct` and
`ConfigProto` classes. This prevents modification of the original
proto data when creating a struct out of a reference
*  Both `clone` methods are nearly identical. Tried to implement `clone`
in the common parent `ConfigStructLike` but did not work.
Fixes #55
> Adds a class specific `clone` method for struct & proto

- README.md
- cpp/config_actions.h
- cpp/config_grammar.h
*  A reference key/name may be assigned to a variable via the special
keyword `$PARENT_NAME`. See `README.md` for details.
Addresses #41
> Allows reference name to be assigned to variable

- .clang-tidy
- cpp/config_build.cpp
- cpp/config_reader_example.cpp
- cpp/config_selector.h
- cpp/math_actions.h
- tests/.clang-tidy
- tests/config_exception_test.cpp
- tests/config_grammar_test.cpp
- tests/config_helpers_test.cpp
- tests/config_parse_test.cpp
- tests/math_test.cpp
- tests/utils_test.cpp
*  Addresses possible exception in main
*  Address clang-tidy issues in all tests
*  Adds ignore rule for macros in cognitive complexity check
> Addresses additional clang-tidy warnings

- README.md
- include/flexi_cfg/config/actions.h
- include/flexi_cfg/config/classes.h
- include/flexi_cfg/config/grammar.h
- include/flexi_cfg/config/reader.h
- src/config_reader.cpp
- tests/config_grammar_test.cpp
- tests/config_helpers_test.cpp
- tests/config_parse_test.cpp
*  Support boolean values of type `true` or `false`
*  Previously, `0` or `1` were allowed as boolean types. This functionality has been removed.
> Add bool type support

- examples/config_example5.cfg
- include/flexi_cfg/config/reader.h
- src/config_helpers.cpp
- src/config_reader.cpp
- tests/config_grammar_test.cpp
- tests/config_helpers_test.cpp
Instead of throwing the `map::at` exception, throw the `InvalidKeyException` with some additional information to help trace the failure.
> Missing final key exception

- examples/config_example5.cfg
- include/flexi_cfg/config/actions.h
- include/flexi_cfg/config/grammar.h
- src/config_helpers.cpp
- src/config_reader.cpp
- tests/config_grammar_test.cpp
*  Adds new rule for a `PROTO_LIST` which handles `VAR` elements in a list
*  Handles resolving of `kVar` elements within a `kList` object
*  Adds test cases for `LIST` grammar rule
*  Further cleans up config_grammar_test
Addresses #72
> Adds support for kVar type in kList

- include/flexi_cfg/reader.h
Since Reader no longer has all the parsing logic tied to it, it is now just a container that stores some data. Semantically, a data container should have an empty base state. This will help with the ergonomics of using the Reader as well.
> Enable default constructor for Reader

- examples/config_example5.cfg
- include/flexi_cfg/config/classes.h
- include/flexi_cfg/reader.h
- src/config_reader.cpp
- src/config_reader_example.cpp
*  Adds examples for reading objects of type `std::vector<std::vector<T>>` from a config file.
> Adds support for nested std::vector<T> objects

- include/flexi_cfg/config/classes.h
- include/flexi_cfg/config/exceptions.h
- include/flexi_cfg/logger.h
- include/flexi_cfg/reader.h
- src/config_reader.cpp
*  Fixes an issue that prevented `$PARENT_NAME` from being used within a string just like proto-vars can be used.
*  Improves error messages when config entry is not found
*  Adds some log helper macros
> Improves usage of `$PARENT_NAME` keyword

- examples/config_example1.cfg
- python/flexi_cfg_py.cpp
- python/test_flexi_cfg.py
- src/config_reader.cpp
* Fix accessing of unsigned `int`s. Calling `getValue<uint64_t>` on a negative int led to integer underflow . Now parsing a negative int as an unsigned results in an exception.
> Properly register exceptions in pybind 11

- .github/workflows/cmake.yml
- README.md
- examples/config_example12.cfg
- examples/nested/config_nested1.cfg
- examples/nested/config_nested2.cfg
- include/flexi_cfg/config/actions.h
- include/flexi_cfg/config/grammar.h
- python/CMakeLists.txt
* Adds new keyword `include_relative` to allow nested includes to resolve paths relatively
* Adds nested include test
* Removes deprecated pybind11-stubgen CLI arguments
> Fix include path handling in nested includes

- .github/workflows/cmake.yml
- README.md
- examples/config_example13.cfg
- examples/env/env_example1.cfg
- examples/env/env_example2.cfg
- include/flexi_cfg/config/actions.h
- include/flexi_cfg/config/grammar.h
- include/flexi_cfg/config/selector.h
- include/flexi_cfg/utils.h
- src/config_helpers.cpp
- tests/config_exception_test.cpp
Added support for environment variables in include statements using the syntax: `${VAR}`
> Support environment variables in include statements

- examples/config_root/test/config_example_base.cfg
- examples/config_root/test/config_relative.cfg
- examples/nested/config_nested3.cfg
- include/flexi_cfg/config/actions.h
- include/flexi_cfg/parser.h
- python/flexi_cfg_py.cpp
- python/test_flexi_cfg.py
- src/config_parser.cpp
- tests/config_exception_test.cpp
- tests/config_parse_test.cpp
*  Previously the root of the config directory was assumed to be the parent directory of the config file.
This functionality is still supported if the root directory is not specified
*  The user may optionally specify a "root" directory for all config files and a path relative to the base config file
> Adds support for specifying the root of the config directory

- .github/workflows/cmake.yml
- include/flexi_cfg/config/classes.h
- include/flexi_cfg/config/grammar.h
- tests/config_grammar_test.cpp
- tests/config_parse_test.cpp
*  Addresses issue 113 by allowing inline comments within a list
*  Addresses issue 125 by allowing empty lists
> Issue 113: list enhancements

- CMakeLists.txt
- Dockerfile
- README.md
- examples/config_example16.cfg
- examples/config_example16_base.cfg
- examples/config_example16_overlay.cfg
- include/flexi_cfg/reader.h
- include/flexi_cfg/visitor-internal.h
- include/flexi_cfg/visitor-json.h
- include/flexi_cfg/visitor.h
- python/CMakeLists.txt
- python/flexi_cfg_py.cpp
- python/test_flexi_cfg.py
- requirements.txt
- src/config_reader.cpp
- tests/config_parse_test.cpp
Frequently requested feature is a JSON representation of a materialized FlexiConfig, this PR adds:
- a `<concepts>` based `Reader::visit(..)` API to walk the materialized config tree
- enable a `dump(..)` to a custom `ostream`
- a basic and pretty printing JSON visitor
- `python` bindings for `Reader::dump()` and `Reader::json(pretty=true)`
- tests C++ JSON visitor
- JSON is validated by the python JSON parser through the python bindings
- updated readme
- enable `python` testing from `Docker`
- fixed CMake Python integration, python test was not included in `ctest` and possibly not running in CI
> Config visitor API with JSON implementation

- README.md
- examples/config_example17.cfg
- examples/config_example5.cfg
- include/flexi_cfg/config/grammar.h
- src/config_helpers.cpp
- src/config_reader_example.cpp
- tests/config_grammar_test.cpp
- tests/config_parse_test.cpp
*  Modifies `LIST` grammer to support `EXPRESSION` types in lists.
*  Expressions are only supported if the other elements of the list resolve to a number type
*  Adds additional test coverage for expression in list support
Resolves #149
> [fix] Support expression types in lists

- examples/config_example13.cfg
- examples/env/env_example2.cfg
- examples/env/env_example3.cfg
- include/flexi_cfg/config/actions.h
- src/config_parser.cpp
The include_relative directive was not correctly resolving paths relative to the current file. This change updates the logic in `base_include_action::apply` to use the parent directory of the current file (`in.position().source`) as the base for relative includes.
If the input is from a string (i.e., `in.position().source` is empty), it falls back to `out.base_dir`.
This commit also includes the patch from issue #159 to make `parseCommon` throw an exception on parsing failure, aiding in debugging and surfacing such issues.
Additionally, `examples/config_example13.cfg` was updated to use correct paths for its includes, and the test environment now ensures `TEST_DIR` is properly set.
> Fix(include_relative): Correctly resolve relative include paths
